CREATE SCHEMA IF NOT EXISTS CAPITOLE;

CREATE TABLE CAPITOLE.PEDIDOS (
    ID_PEDIDO NUMERIC(16,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ID_USUARIO NUMERIC(16,0),
    ID_TIENDA NUMERIC(16,0),
    FECHA TIMESTAMP ,
    TOTAL NUMERIC(16,0) DEFAULT 0,
    SUBTOTAL NUMERIC(16,0) DEFAULT 0,
    DIRECCION VARCHAR(100) ,
    CP VARCHAR(20) ,
    POBLACION VARCHAR(100) ,
    PAISCC2 VARCHAR(2) ,
    ID_ESTADO NUMERIC(16,0),
    CONSTRAINT PEDIDOS_PK PRIMARY KEY (ID_PEDIDO)
);


COMMENT ON TABLE CAPITOLE.PEDIDOS IS 'Pedidos';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.ID_PEDIDO IS 'Identificador';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.ID_USUARIO IS 'Usuario';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.ID_TIENDA IS 'Tienda';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.FECHA IS 'Fecha que se realiza el pedio';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.TOTAL IS 'Total';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.SUBTOTAL IS 'Subtotal';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.DIRECCION IS 'Direccion de envio';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.CP IS 'Codigo postal de envio';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.POBLACION IS 'Poblacion de envio';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.PAISCC2 IS 'Pais de envio';
COMMENT ON COLUMN CAPITOLE.PEDIDOS.ID_ESTADO IS 'Estado del pedido';



CREATE TABLE CAPITOLE.USUARIOS (
    ID_USUARIO NUMERIC(16,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOMBRE VARCHAR(50),
    APELLIDO1 VARCHAR(50) ,
    APELLIDO2 VARCHAR(50) ,
    DIRECCION VARCHAR(100) ,
    CP VARCHAR(20) ,
    POBLACION VARCHAR(100) ,
    PAISCC2 VARCHAR(2) ,
    CONSTRAINT USUARIOS_PK PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE CAPITOLE.TIENDAS (
    ID_TIENDA NUMERIC(16,0) GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOMBRE VARCHAR(50),
    CONSTRAINT TIENDAS_PK PRIMARY KEY (ID_TIENDA)
);

